print ("Diario de un Astronauta\n")
print ("=" * 30)
print ("Fecha: 2024-01-10")
print ("=" * 30)
print("Hoy visite el espacio\n")
print("Mensaje personal: Exploto mi casa!\n")
print ("=" * 30)
print("Fecha: 2024-01-11")
print ("=" * 30)
print ("Hoy visite la luna\n")
print("Mensaje personal: Me siento muy satisfecho!\n")